name: Deploy workspaces

on:
  workflow_call:
    inputs:
      workspaces:
        required: true
        type: string
    secrets:
      tfc-token:
        required: true
      tfe-token:
        required: true

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: mdmsua/aks-tfe
    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.tfc-token }}
    - run: |
        terraform init
        terraform validate
        terraform plan -out terraform.tfplan
        terraform apply -auto-approve terraform.tfplan
      env:
        TFE_TOKEN: ${{ secrets.tfe-token }}
        TF_VAR_workspaces: ${{ inputs.workspaces }}
    